---
spring:
  profiles: cloudpeers
eureka:
  client:
    serviceUrl:
      defaultZone: ${http://${PREFIX:}othereureka.${application.domain:cfapps.io}}/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
