spring:
  profiles.active: cloud
---
spring:
  profiles: cloud
  jpa:
    show_sql: false
    database: MYSQL
    hibernate:
      ddl-auto: none
server:
  port: 9006
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
